### PR TITLE
Add PBR support

### PR DESCRIPTION
**Pull request by LegendaryGuard**
PBR support. [What is PBR (Physically Based Rendering)?](https://en.wikipedia.org/wiki/Physically_based_rendering)

### CODE REVIEW

**Comment by LegendaryGuard** [comment]
I tested locally on Windows and builds correctly, I missed something for Linux. I wonder what is.

**Comment by LegendaryGuard** [comment]
Maybe capital letters are case sensitive in vpc files when Linux compiles.

**Comment by magisk666** [comment]
Thank you for your code contribution. This action can make the engine more advanced. I hope it can speed up the recommendation of the adaptation of Linux and Android.

**Comment by LegendaryGuard** [comment]
Nice, ready to be merged. @nillerusr, please feel free to take a look as you wish. 🙇

**Comment by HappyDOGE** [comment]
Any in-game screenshots and example materials?

**Comment by EnderZip** [comment]
image
image

**Comment by EnderZip** [comment]
Although I doubt nillerusr is gonna merge this, the shader is using sm3 but togl only support <2.0b atm

**Comment by LegendaryGuard** [comment]
Should look this: https://developer.valvesoftware.com/wiki/Adding_PBR_to_Your_Mod to update the code?
Any objections?

**Comment by EnderZip** [comment]
Use the ps20b version of the shader, other than that sure go ahead

**Comment by LegendaryGuard** [comment]
> Use the ps20b version of the shader, other than that sure go ahead

I just uploaded these files to support. I think, if I'm not mistaken, supports both (2.0b and 3.0), right?

**Comment by EnderZip** [comment]
yea

**Comment by LegendaryGuard** [comment]
I noticed physics props turn black when `r_PhysPropStaticLighting` is 1 (when used with the PBR shader after 2-3 seconds due to Prop Sleeping). Reference: https://developer.valvesoftware.com/wiki/Adding_PBR_to_Your_Mod#Fixes

**Comment by LegendaryGuard** [comment]
I tried to talk and convince nillerusr about that, I think he thought it was an inconvenience, idk what's. Someone told that something has been broken, maybe this guy didn't update to the last PBR commit, finding out that it's a fix that prevents PBR props from turning black. I tested in HL2 without PBR, there have been no crashes nor even graphical glitches. I don't find the inconvenience here, the engine isn't made to support PBR? 

I feel sorry for these guys who were eager, I understand it's something cool for graphics and optionally those shaders can be set if the modders want. And I didn't find any error about that implementation. 

I think we could also put this stuff in a separate branch in this repository, it would be a good idea.

**Comment by magisk666** [comment]
This is a good thing. Does Android support it?

**Review by halotroop2288 — APPROVED** [review]

**Pull request merged**
