### PR TITLE
Add artifacts to download the compiled resources on GitHub

### PR DESCRIPTION
**Pull request by LegendaryGuard**
**What is?**

The artifacts are resources where the users can download in GitHub without doing a task in the repository like compiling and getting the compiled resources. Made to ease the development progress and give access to the testers.

Contains the compiled source files and can be debug opening Visual Studio to capture some exceptions or bugs. Also can copy and paste source files to test the engine in the game.

Every time gets commits, the workflow runs and upload artifacts to download.

- In the GitHub repository, go to: 

**Actions** >> 
image

<br/>

**Select workflow (select the build one, not the tests) or click View Workflow file from suspension points button** >> 

image

<br/>

**Scroll down and you'll see the artifacts to download** >> **Download some artifact you want to test**

image

### CODE REVIEW

**Comment by nillerusr** [comment]
NOPE - :)

**Comment by nillerusr** [comment]
I know what is artifacts, thks

**Comment by nillerusr** [comment]
Although uploading builds is not for android. I don't mind. But it's better to do it differently

**Comment by LegendaryGuard** [comment]
🆗 👍 
What you think is convenient.

**Review by stephen-cusi — COMMENTED** [review]
You can remove the source code and use regular expressions to match the corresponding binary packages.

**Comment by stephen-cusi** [comment]
> 您可以删除源代码并使用正则表达式来匹配相应的二进制包。



> You can remove the source code and use regular expressions to match the corresponding binary packages.

In order to reduce the file size, and my branch needs your automatic build and release, haha

**Comment by nillerusr** [comment]
@stephen-cusi 
Your branch is a bruh

**Comment by LegendaryGuard** [comment]
I don't think nillerusr will accept that anymore and due to some reasons. Even it could be cool to have this.

Btw, I just enhanced the workflows for the artifacts. I did that the workflow removes the .o and .pdb files in the artifacts and I made some tweaks in `build.yml` and `scripts/*.sh` in my [artifacts branch](https://github.com/LegendaryGuard/source-engine/tree/artifacts). I tested with `./waf configure -T release` and works too.

So, now, the artifacts have less file size: 
- **debug** (default)
image

- **release**
image

<br/>
<br/>

**Comment by LegendaryGuard** [comment]
Done! I just cleaned the unnecessary files and empty directories in the artifacts. Anyone can copy my [**build.yml**](https://github.com/LegendaryGuard/source-engine/blob/artifacts/.github/workflows/build.yml) content as you want.

**Comment by LegendaryGuard** [comment]
Just heads up, I improved the artifacts to extract the compiled files neatly. Whereas, `bin` is for `bin` folder; `game/bin` is for inside game bin folder (e.g. `hl2/bin`), plus `launcher.exe` is located in the root folder.

**Comment by JuneCoreEngine** [comment]
This is still needed

**Pull request closed without merging**
