### PR TITLE
Delete launcher/android/crashhandler.cpp

### PR DESCRIPTION
**Pull request by coderamen666**
Comply with xash3d dmca request

This would disable Android support unless it is rewritten

### CODE REVIEW

**Comment by nillerusr** [comment]
it is impossible to write it differently using libunwind. I won't delete it.  This dmca is not correct and is aimed just to give me a  shit.  
Why should I rewrite this it if I wrote it myself from documentation?

**Comment by coderamen666** [comment]
> it is impossible to write it differently using libunwind. I won't delete it. This dmca is not correct and is aimed just to give me a shit. Why should I rewrite/delete this it if I wrote it myself from documentation?

This DMCA could get this repository taken down. That is why I am concerned. Maybe I was just overreacting.

Investigating further because I got the DMCA email right before I went to sleep and didn't dig deeper, there is exactly one function that is uncannily similar.

https://github.com/tyabus/xash3d/blob/master/engine/platform/posix/crashhandler_libunwind.c#L105

https://github.com/nillerusr/source-engine/blob/master/launcher/android/crashhandler.cpp#L144

**Comment by nillerusr** [comment]
Of course it similiar.

How do you suggest handling signals in Linux another way?

Look. This function is similar too
https://github.com/FWGS/xash3d/blob/master/engine/common/crashhandler.c#L373

oops

**Comment by nillerusr** [comment]
Original copyright by mittorn, oooops

**Comment by nillerusr** [comment]
https://gist.github.com/JCash/95f3d3aee4b626a4ee0499a3503ad303#file-signal_test-c-L133
Random file from github: oops, looks similar

**Comment by nillerusr** [comment]
Anyway I rejected this stupid takedown from tyabus. He's just trying to hurt me. Don't pay attention for it

**Pull request closed without merging**
