### PR TITLE
fixed compile for dedicated_server on win32 (and maybe linux)

### PR DESCRIPTION
**Pull request by rwf93**
I haven't tested compiling for linux. It also won't build on Android for obvious reasons. 

It won't run with the VGUI popup, but at least -console flag will work.

Note, it won't compile with -d (--dedicated) on configure, I have absolutely no clue why. I'll have to look into it more later.

### CODE REVIEW

**Comment by rwf93** [comment]
I should have mentioned, I noticed with powershell that the `-game` parameter would be messed up, this would cause the function `COM_CheckGameDirectory` to return false.

**Comment by nillerusr** [comment]
:clown_face:

**Comment by nillerusr** [comment]
Let's meet - github action https://github.com/nillerusr/source-engine/actions/runs/2896539442

**Comment by nillerusr** [comment]
special4you
image

**Comment by rwf93** [comment]
shame, my bad then

**Pull request closed without merging**
