### PR TITLE
Fix Linux build errors, Update README

### PR DESCRIPTION
**Pull request by WitherOrNot**
This PR is to fix build errors on Linux and clarify the build instructions, as constructed in #69

For a complete build error fix, see also nillerusr/source-physics#3

### CODE REVIEW

**Comment by nillerusr** [comment]
1. https://github.com/nillerusr/source-engine/blob/master/public/engine/thinktracecounter.h
Already in master
2. Opus should be optional, not removed

**Comment by LegendaryGuard** [comment]
Better don't remove `'engine/voice_codecs/opus'` from wscript, because needs to find the required lib to be fixed. Besides sounds and music, also it's used for voices and audio recordings.

About `#ifndef _PS3`, I don't know what's broken, it was used for PS3 devices. If it's deprecated or something like that, it would be ok write `#if 0 // #ifndef _PS3` instead. The comment may remember what needs to build PS3.

**Comment by LegendaryGuard** [comment]
Oh, wait, no!

The include inside `#ifndef _PS3` is incorrect. This [`thinktracecounter.h`](https://github.com/nillerusr/source-engine/blob/master/public/engine/thinktracecounter.h) that @nillerusr mentioned is in `public/engine/thinktracecounter.h`.
`engine/thinktracecounter.h` doesn't exist in engine directory. Really it's located in public/engine directory!

**Comment by LegendaryGuard** [comment]
About `_PS3`, ignore the previous messages. Just leave as it should, I just built again and the error doesn't show when using `#ifndef _PS3`. I don't know what exactly happened when I was doing that moment: https://github.com/nillerusr/source-engine/issues/69#issuecomment-1171556913

**Comment by LegendaryGuard** [comment]
Why not to add the 32 bits build steps on README?

**Pull request closed without merging**
