### PR TITLE
osx arm64 port

### PR DESCRIPTION
**Pull request by MoeMod**
I've tested cstrike with apple silicon. vgui2 works fine, while mdl loading and rendering is still buggy.
compiled with latest Xcode 13.2.1 on macOS 11.6.3
-DPLATFORM_64BITS=1 -DOSX -D_OSX -DPOSIX -D_POSIX -DGNUC -DNO_HOOK_MALLOC -DNO_MALLOC_OVERRIDE

### CODE REVIEW

**Comment by klaymen1n** [comment]
Wow, man good work

**Comment by magisk666** [comment]
How about on arm64 linux or other (like Android)?

**Comment by davie504** [comment]
Nice PR

**Comment by nillerusr** [comment]
Ok, I'll check it on amd64

**Pull request merged**
