### PR TITLE
[WIP] Import Changes from Mapbase

### PR DESCRIPTION
**Pull request by halotroop2288**
Not exactly a "merge" because I would have liked to preserve commit history, but I (will) have imported all the changes at once since that is likely impossible.

This is a heavy work in progress. When it's done, it should allow Mapbase mods to be more easily ported to this engine.

Differences from Mapbase:
- Duplicated fixes and additions ignored (easily noticed when doing this by hand)
- Squirrel is a submodule of the official Git repo (reduces manual work)
- Any newly added preprocessor block has a commented endif to help keep track in less featured editors
- Ignored `memoverride.cpp` changes for fear of fucking it up

TO-DO:
- [ ] Import all the code changes [320/1417 files addressed](https://github.com/halotroop2288/source-sdk-base/pull/2/files?w=1)
- [ ] Finish writing up wscripts
- [ ] Working Waf Squirrel support for VScript
- [ ] Fix build errors and solve other issues
- [ ] Address contributor concerns

I highly recommend turning on the "ignore whitespace changes" setting while reviewing. VS Code auto-formatted trailing whitespace out of any modified file.

### CODE REVIEW

**Comment by nillerusr** [comment]
Well that's may be useful for sdk, not for engine

**Comment by nillerusr** [comment]
I have good script-helpers for doing task like that

**Comment by halotroop2288** [comment]
> Well that's may be useful for sdk, not for engine

What's the big difference? SDK is just supposed to be a subset of engine anyway, right? (Serious question. I'm not *that* familiar.)

**Comment by halotroop2288** [comment]
> Well that's may be useful for sdk, not for engine

Would you still be interested in the minor bug fixes and optimizations Mapbase added (basically anything outside a preprocessor block)?

**Comment by nillerusr** [comment]
@halotroop2288
> Would you still be interested in the minor bug fixes and optimizations Mapbase added (basically anything outside a preprocessor block)?
I am not interesting in that for hl2 and master branch, because it have fixes from me and easily may break something.
But I am interesting in mapbase in separate branch for mods that's using mapbase like entropy zero 2

**Comment by halotroop2288** [comment]
> But I am interesting in mapbase in separate branch for mods that's using mapbase like entropy zero 2

Oh gotcha. I can retarget this PR to a different upstream branch if you want.
Also, could you tell me more about those helper scripts?

**Comment by steadyfield** [comment]
@halotroop2288 is this work of porting mapbase to nillerusr's source engine still active? or it is cancelled?

**Comment by halotroop2288** [comment]
> Is this work of porting mapbase to nillerusr's source engine still active?

Suspended for now, real life is in the way.

**Comment by IAhmadGT** [comment]
still waiting :D

**Comment by halotroop2288** [comment]
I'm not working on this anymore, I'm leaving it up so others can continue where I left off though.

**Comment by halotroop2288** [comment]
We're getting shut down. Godspeed. o7

**Pull request closed without merging**
