### PR TITLE
VPC Support for Visual Studio 2022

### PR DESCRIPTION
**Pull request by halotroop2288**
This adds support for Visual Studio 2022 to VPC.
I understand that you don't use VPC for this project anymore, but it may be useful to others who still prefer it.

In the event that you decide to fully drop support for VPC, or would like to offload the responsibility for it to a third party, I'll be hosting it by itself at: https://github.com/halotroop2288/vpc

### CODE REVIEW

**Comment by Er2ch** [comment]
IMHO waf is better than vpc.
waf supports solution generation and macOS (x64 and aarch64 such as M1).
Also migration from vpc to wscript isn't hard, so I don't know who really want to use vpc.

**Comment by nillerusr** [comment]
That's really useless.
vpc generates .sln files. waf can do that too. Also my waf extension can parse vpc files, maybe i will add full vpc support to waf later. But this is enough for client/server parts

**Comment by halotroop2288** [comment]
Well I'm not too happy about this being closed just because of that, but oh well.
I'll play along:

> my waf extension can parse vpc files

Do you mind explaining how to use it for that? There's not much in the way of contributor documentation here. 😅

**Comment by Er2ch** [comment]
Are you Valve’s slave?

**Comment by Headofacrab** [comment]
vpc is better and simpler. waf is gay

**Comment by mittorn** [comment]
vpc and visual studio is likely to is likely to be scam

**Pull request closed without merging**
