### PR TITLE
Disable touch transparent in multiplayer game

### PR DESCRIPTION
**Pull request by AruMoon**

### CODE REVIEW

**Comment by steadyfield** [comment]
Is this for anti-cheat? if it is, in my opinion you cannot simply prevent cheating by disabling touch transparent. They can do it in many other ways.

**Comment by AruMoon** [comment]
> Is this for anti-cheat? if it is, in my opinion you cannot simply prevent cheating by disabling touch transparent. They can do it in many other ways.

No, it disables touch transparent, that should be only in cutscenes. There is a bug, that in multiplayer games after a few changelevels touch becomes transparent, when it shouldn't. This PR just disables this feature in multiplayer games

**Comment by steadyfield** [comment]
> > Is this for anti-cheat? if it is, in my opinion you cannot simply prevent cheating by disabling touch transparent. They can do it in many other ways.
> 
> No, it disables touch transparent, that should be only in cutscenes. There is a bug, that in multiplayer games after a few changelevels touch becomes transparent, when it shouldn't. This PR just disables this feature in multiplayer games

Thank you for explanation. And that reminds me of an other bug, about the game_ui entity. In the latest android version, when a game_ui entity is activated, the player's view is freezed and cannot move at all and all the touch buttons are hidden. The windows version is working fine. In an old android version, it does not have this bug.

**Comment by AruMoon** [comment]
Fixed in https://github.com/nillerusr/source-engine/commit/601cfff16404f7c970143b1313a7b89c6ea55d78

**Pull request closed without merging**
