### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by HappyDOGE**
VS2015 required
64bit needs physics fixes

### CODE REVIEW

**Comment by HappyDOGE** [comment]
@LegendaryGuard try using Windows SDK 10.0.19041.0

**Comment by boris768** [comment]
add no except, _msize_base should be:
`size_t _msize_base( void *pMem ) _CRT_NOEXCEPT`

**Comment by HappyDOGE** [comment]
@boris768 not all windows sdk versions have noexcept for that function, what would be the best way to check for that?

**Comment by HappyDOGE** [comment]
@LegendaryGuard please try latest commit

**Comment by boris768** [comment]
@HappyDOGE i think, need to freeze used toolchain for each platform and compiler. it is up to the @nillerusr to make this decision.

**Comment by LegendaryGuard** [comment]
@HappyDOGE I updated to the latest commit. Almost here! Reached: [2210/2286]

```batch
[2204/2286] Linking build\vphysics\vphysics.dll
17:55:26 runner ['C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX86\\x86\\LINK.exe', '/nologo', '/MANIFEST', '/nologo', '/MANIFEST', '/DEBUG', '/INCREMENTAL', '/NODEFAULTLIB:libc', '/NODEFAULTLIB:libcd', '/NODEFAULTLIB:libcmtd', '/LIBPATH:C:\\msys64\\home\\user\\happydoge\\source-engine/lib/win32/x86/', '/LIBPATH:C:\\msys64\\home\\user\\happydoge\\source-engine/dx9sdk/lib/x86/', '/subsystem:WINDOWS,5.01', '/IMPLIB:vphysics\\vphysics.lib', '/DLL', 'vphysics\\convert.cpp.42.o', 'public\\filesystem_helpers.cpp.42.o', 'vphysics\\ledgewriter.cpp.42.o', 'vphysics\\main.cpp.42.o', 'vphysics\\physics_airboat.cpp.42.o', 'vphysics\\physics_collide.cpp.42.o', 'vphysics\\physics_constraint.cpp.42.o', 'vphysics\\physics_controller_raycast_vehicle.cpp.42.o', 'vphysics\\physics_environment.cpp.42.o', 'vphysics\\physics_fluid.cpp.42.o', 'vphysics\\physics_friction.cpp.42.o', 'vphysics\\physics_material.cpp.42.o', 'vphysics\\physics_motioncontroller.cpp.42.o', 'vphysics\\physics_object.cpp.42.o', 'vphysics\\physics_shadow.cpp.42.o', 'vphysics\\physics_spring.cpp.42.o', 'vphysics\\physics_vehicle.cpp.42.o', 'vphysics\\physics_virtualmesh.cpp.42.o', 'vphysics\\trace.cpp.42.o', 'vphysics\\vcollide_parse.cpp.42.o', 'vphysics\\vphysics_saverestore.cpp.42.o', 'public\\tier0\\memoverride.cpp.42.o', '/OUT:C:\\msys64\\home\\user\\happydoge\\source-engine\\build\\vphysics\\vphysics.dll', '/LIBPATH:ivp\\havana', '/LIBPATH:ivp\\havana\\havok\\hk_math', '/LIBPATH:ivp\\havana\\havok\\hk_base', '/LIBPATH:ivp\\ivp_compact_builder', '/LIBPATH:ivp\\ivp_physics', '/LIBPATH:tier1', '/LIBPATH:tier2', '/LIBPATH:mathlib', 'havana_constraints.lib', 'hk_math.lib', 'hk_base.lib', 'ivp_compactbuilder.lib', 'ivp_physics.lib', 'tier1.lib', 'tier2.lib', 'mathlib.lib', '/LIBPATH:C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\ATLMFC\\lib\\x86', '/LIBPATH:C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\lib\\x86', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.6.1\\lib\\um\\x86', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.20348.0\\ucrt\\x86', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\\\lib\\10.0.20348.0\\\\um\\x86', '/LIBPATH:C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\ATLMFC\\lib\\x86', '/LIBPATH:C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\lib\\x86', '/LIBPATH:C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\lib\\x86\\store\\references', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\UnionMetadata\\10.0.20348.0', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\References\\10.0.20348.0', '/LIBPATH:C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319', '/LIBPATH:vstdlib', '/LIBPATH:tier0', 'vstdlib.lib', 'tier0.lib', 'advapi32.lib', 'ws2_32.lib', 'rpcrt4.lib']
[2207/2286] Linking build\unicode\unicode.dll
17:55:26 runner ['C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX86\\x86\\LINK.exe', '/nologo', '/MANIFEST', '/nologo', '/MANIFEST', '/DEBUG', '/INCREMENTAL', '/NODEFAULTLIB:libc', '/NODEFAULTLIB:libcd', '/NODEFAULTLIB:libcmtd', '/LIBPATH:C:\\msys64\\home\\user\\happydoge\\source-engine/lib/win32/x86/', '/LIBPATH:C:\\msys64\\home\\user\\happydoge\\source-engine/dx9sdk/lib/x86/', '/subsystem:WINDOWS,5.01', '/IMPLIB:unicode\\unicode.lib', '/DLL', 'unicode\\unicode.cpp.46.o', 'public\\tier0\\memoverride.cpp.46.o', '/OUT:C:\\msys64\\home\\user\\happydoge\\source-engine\\build\\unicode\\unicode.dll', '/LIBPATH:tier1', '/LIBPATH:tier2', '/LIBPATH:mathlib', 'tier1.lib', 'tier2.lib', 'mathlib.lib', '/LIBPATH:C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\ATLMFC\\lib\\x86', '/LIBPATH:C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\lib\\x86', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.6.1\\lib\\um\\x86', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.20348.0\\ucrt\\x86', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\\\lib\\10.0.20348.0\\\\um\\x86', '/LIBPATH:C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\ATLMFC\\lib\\x86', '/LIBPATH:C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\lib\\x86', '/LIBPATH:C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\lib\\x86\\store\\references', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\UnionMetadata\\10.0.20348.0', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\References\\10.0.20348.0', '/LIBPATH:C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319', '/LIBPATH:vstdlib', '/LIBPATH:tier0', 'vstdlib.lib', 'tier0.lib', 'advapi32.lib', 'ws2_32.lib', 'rpcrt4.lib', 'user32.lib']
[2210/2286] Linking build\launcher_main\hl2_launcher.exe
17:55:26 runner ['C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX86\\x86\\LINK.exe', '/nologo', '/MANIFEST', '/nologo', '/MANIFEST', '/DEBUG', '/INCREMENTAL', '/NODEFAULTLIB:libc', '/NODEFAULTLIB:libcd', '/NODEFAULTLIB:libcmtd', '/LIBPATH:C:\\msys64\\home\\user\\happydoge\\source-engine/lib/win32/x86/', '/LIBPATH:C:\\msys64\\home\\user\\happydoge\\source-engine/dx9sdk/lib/x86/', '/subsystem:WINDOWS,5.01', 'launcher_main\\main.cpp.20.o', 'launcher_main\\launcher_main.res', '/OUT:C:\\msys64\\home\\user\\happydoge\\source-engine\\build\\launcher_main\\hl2_launcher.exe', '/LIBPATH:C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\ATLMFC\\lib\\x86', '/LIBPATH:C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\lib\\x86', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.6.1\\lib\\um\\x86', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.20348.0\\ucrt\\x86', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\\\lib\\10.0.20348.0\\\\um\\x86', '/LIBPATH:C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\ATLMFC\\lib\\x86', '/LIBPATH:C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\lib\\x86', '/LIBPATH:C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\lib\\x86\\store\\references', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\UnionMetadata\\10.0.20348.0', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\References\\10.0.20348.0', '/LIBPATH:C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319', 'user32.lib', 'shell32.lib']
[2211/2286] Compiling lib\win32\x86\SDL2.dll
17:55:26 runner ' cp ..\\lib\\win32\\x86\\SDL2.dll inputsystem\\SDL2.dll '
+ install C:\Users\victo\AppData\Local\Temp\bin\datacache.lib (from build\datacache\datacache.lib)
- install C:\Users\victo\AppData\Local\Temp\bin\datacache.dll (from build\datacache\datacache.dll)
"cp" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

   Creando biblioteca unicode\unicode.lib y objeto unicode\unicode.exp

   Creando biblioteca C:\msys64\home\user\happydoge\source-engine\build\launcher_main\hl2_launcher.lib y objeto C:\msys64\home\user\happydoge\source-engine\build\launcher_main\hl2_launcher.exp

17:55:26 runner ['C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.20348.0\\\\x86\\MT.exe', '/nologo', '-manifest', 'C:\\msys64\\home\\user\\happydoge\\source-engine\\build\\unicode\\unicode.dll.manifest', '-outputresource:C:\\msys64\\home\\user\\happydoge\\source-engine\\build\\unicode\\unicode.dll;2']
17:55:26 runner ['C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.20348.0\\\\x86\\MT.exe', '/nologo', '-manifest', 'C:\\msys64\\home\\user\\happydoge\\source-engine\\build\\launcher_main\\hl2_launcher.exe.manifest', '-outputresource:C:\\msys64\\home\\user\\happydoge\\source-engine\\build\\launcher_main\\hl2_launcher.exe;1']
   Creando biblioteca vphysics\vphysics.lib y objeto vphysics\vphysics.exp

17:55:27 runner ['C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.20348.0\\\\x86\\MT.exe', '/nologo', '-manifest', 'C:\\msys64\\home\\user\\happydoge\\source-engine\\build\\vphysics\\vphysics.dll.manifest', '-outputresource:C:\\msys64\\home\\user\\happydoge\\source-engine\\build\\vphysics\\vphysics.dll;2']
Waf: Leaving directory `C:\msys64\home\user\happydoge\source-engine\build'
Build failed
 -> task in 'SDL2.dll' failed with exit status 1:
        {task 2245697479712: SDL2.dll SDL2.dll -> SDL2.dll}
' cp ..\\lib\\win32\\x86\\SDL2.dll inputsystem\\SDL2.dll '
```

**Comment by LegendaryGuard** [comment]
I used Windows CMD, I think `cp` command is from Linux. I'll try with Windows Powershell.

**Comment by HappyDOGE** [comment]
oh whoops, I will fix that soontm

**Comment by HappyDOGE** [comment]
@LegendaryGuard try again pls

**Comment by LegendaryGuard** [comment]
@HappyDOGE 
Finally, the waf build on Windows has been successfull! 🎉  <br/> @nillerusr will have to review your changes. I hope Windows waf build is case solved soon.
```batch
[2199/2286] Linking build\vgui2\src\vgui2.dll
physics_vehicle.cpp

[2200/2286] Processing vphysics\physics_motioncontroller.cpp
[2201/2286] Processing vphysics\main.cpp
[2202/2286] Processing public\tier0\memoverride.cpp
physics_controller_raycast_vehicle.cpp

[2203/2286] Processing unicode\unicode.cpp
physics_material.cpp

[2204/2286] Compiling launcher_main\launcher_main.rc
Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
Copyright (C) Microsoft Corporation.  All rights reserved.


vcollide_parse.cpp

[2205/2286] Processing launcher_main\main.cpp
[2206/2286] Compiling lib\win32\x86\SDL2.dll
        1 archivo(s) copiado(s).

+ install C:\Users\user\AppData\Local\Temp\bin\datacache.lib (from build\datacache\datacache.lib)
+ install C:\Users\user\AppData\Local\Temp\bin\datacache.dll (from build\datacache\datacache.dll)
+ install C:\Users\user\AppData\Local\Temp\bin\datacache.pdb (from build\datacache\datacache.pdb)
physics_constraint.cpp

+ install C:\Users\user\AppData\Local\Temp\bin\engine.dll (from build\engine\engine.dll)
+ install C:\Users\user\AppData\Local\Temp\bin\engine.pdb (from build\engine\engine.pdb)
+ install C:\Users\user\AppData\Local\Temp\bin\engine.lib (from build\engine\engine.lib)
vphysics_saverestore.cpp

+ install C:\Users\user\AppData\Local\Temp\bin\vaudio_minimp3.lib (from build\engine\voice_codecs\minimp3\vaudio_minimp3.lib)
+ install C:\Users\user\AppData\Local\Temp\bin\vaudio_minimp3.dll (from build\engine\voice_codecs\minimp3\vaudio_minimp3.dll)
+ install C:\Users\user\AppData\Local\Temp\bin\vaudio_minimp3.pdb (from build\engine\voice_codecs\minimp3\vaudio_minimp3.pdb)
physics_friction.cpp

+ install C:\Users\user\AppData\Local\Temp\bin\filesystem_stdio.dll (from build\filesystem\filesystem_stdio.dll)
+ install C:\Users\user\AppData\Local\Temp\bin\filesystem_stdio.pdb (from build\filesystem\filesystem_stdio.pdb)
+ install C:\Users\user\AppData\Local\Temp\bin\filesystem_stdio.lib (from build\filesystem\filesystem_stdio.lib)
+ install C:\Users\user\AppData\Local\Temp\hl2\bin\client.dll (from build\game\client\client.dll)
+ install C:\Users\user\AppData\Local\Temp\hl2\bin\client.pdb (from build\game\client\client.pdb)
+ install C:\Users\user\AppData\Local\Temp\hl2\bin\client.lib (from build\game\client\client.lib)
+ install C:\Users\user\AppData\Local\Temp\hl2\bin\server.lib (from build\game\server\server.lib)
+ install C:\Users\user\AppData\Local\Temp\hl2\bin\server.dll (from build\game\server\server.dll)
+ install C:\Users\user\AppData\Local\Temp\bin\GameUI.dll (from build\gameui\GameUI.dll)
+ install C:\Users\user\AppData\Local\Temp\bin\GameUI.pdb (from build\gameui\GameUI.pdb)
+ install C:\Users\user\AppData\Local\Temp\bin\GameUI.lib (from build\gameui\GameUI.lib)
+ install C:\Users\user\AppData\Local\Temp\bin\inputsystem.dll (from build\inputsystem\inputsystem.dll)
+ install C:\Users\user\AppData\Local\Temp\bin\inputsystem.lib (from build\inputsystem\inputsystem.lib)
+ install C:\Users\user\AppData\Local\Temp\bin\inputsystem.pdb (from build\inputsystem\inputsystem.pdb)
+ install C:\Users\user\AppData\Local\Temp\bin\launcher.lib (from build\launcher\launcher.lib)
+ install C:\Users\user\AppData\Local\Temp\bin\launcher.dll (from build\launcher\launcher.dll)
+ install C:\Users\user\AppData\Local\Temp\bin\launcher.pdb (from build\launcher\launcher.pdb)
+ install C:\Users\user\AppData\Local\Temp\bin\materialsystem.lib (from build\materialsystem\materialsystem.lib)
physics_airboat.cpp

+ install C:\Users\user\AppData\Local\Temp\hl2\bin\server.pdb (from build\game\server\server.pdb)
+ install C:\Users\user\AppData\Local\Temp\bin\materialsystem.dll (from build\materialsystem\materialsystem.dll)
trace.cpp

physics_motioncontroller.cpp

unicode.cpp

+ install C:\Users\user\AppData\Local\Temp\bin\materialsystem.pdb (from build\materialsystem\materialsystem.pdb)
physics_environment.cpp

   Creando biblioteca serverbrowser\ServerBrowser.lib y objeto serverbrowser\ServerBrowser.exp

   Creando biblioteca studiorender\studiorender.lib y objeto studiorender\studiorender.exp

memoverride.cpp

[2237/2286] Linking build\vguimatsurface\vguimatsurface.dll
+ install C:\Users\user\AppData\Local\Temp\bin\shaderapidx9.lib (from build\materialsystem\shaderapidx9\shaderapidx9.lib)
+ install C:\Users\user\AppData\Local\Temp\bin\shaderapidx9.dll (from build\materialsystem\shaderapidx9\shaderapidx9.dll)
memoverride.cpp

+ install C:\Users\user\AppData\Local\Temp\bin\shaderapidx9.pdb (from build\materialsystem\shaderapidx9\shaderapidx9.pdb)
+ install C:\Users\user\AppData\Local\Temp\bin\steam_api.dll (from build\thirdparty\StubSteamAPI\steam_api.dll)
+ install C:\Users\user\AppData\Local\Temp\bin\steam_api.pdb (from build\thirdparty\StubSteamAPI\steam_api.pdb)
+ install C:\Users\user\AppData\Local\Temp\bin\steam_api.lib (from build\thirdparty\StubSteamAPI\steam_api.lib)
+ install C:\Users\user\AppData\Local\Temp\bin\tier0.dll (from build\tier0\tier0.dll)
+ install C:\Users\user\AppData\Local\Temp\bin\tier0.lib (from build\tier0\tier0.lib)
+ install C:\Users\user\AppData\Local\Temp\bin\tier0.pdb (from build\tier0\tier0.pdb)
+ install C:\Users\user\AppData\Local\Temp\bin\vstdlib.pdb (from build\vstdlib\vstdlib.pdb)
+ install C:\Users\user\AppData\Local\Temp\bin\vstdlib.lib (from build\vstdlib\vstdlib.lib)
+ install C:\Users\user\AppData\Local\Temp\bin\vstdlib.dll (from build\vstdlib\vstdlib.dll)
+ install C:\Users\user\AppData\Local\Temp\bin\scenefilecache.dll (from build\scenefilecache\scenefilecache.dll)
+ install C:\Users\user\AppData\Local\Temp\bin\scenefilecache.lib (from build\scenefilecache\scenefilecache.lib)
+ install C:\Users\user\AppData\Local\Temp\bin\scenefilecache.pdb (from build\scenefilecache\scenefilecache.pdb)
[2253/2286] Linking build\video\video_services.dll
+ install C:\Users\user\AppData\Local\Temp\bin\soundemittersystem.pdb (from build\soundemittersystem\soundemittersystem.pdb)
+ install C:\Users\user\AppData\Local\Temp\bin\soundemittersystem.lib (from build\soundemittersystem\soundemittersystem.lib)
+ install C:\Users\user\AppData\Local\Temp\bin\soundemittersystem.dll (from build\soundemittersystem\soundemittersystem.dll)
main.cpp

   Creando biblioteca vgui2\src\vgui2.lib y objeto vgui2\src\vgui2.exp

+ install C:\Users\user\AppData\Local\Temp\bin\stdshader_dx9.pdb (from build\materialsystem\stdshaders\stdshader_dx9.pdb)
+ install C:\Users\user\AppData\Local\Temp\bin\stdshader_dx9.lib (from build\materialsystem\stdshaders\stdshader_dx9.lib)
+ install C:\Users\user\AppData\Local\Temp\bin\stdshader_dx9.dll (from build\materialsystem\stdshaders\stdshader_dx9.dll)
main.cpp

[2260/2286] Linking build\vphysics\vphysics.dll
[2261/2286] Linking build\launcher_main\hl2_launcher.exe
   Creando biblioteca video\video_services.lib y objeto video\video_services.exp

- install C:\Users\user\AppData\Local\Temp\bin\SDL2.dll (from build\inputsystem\SDL2.dll)
[2263/2286] Linking build\unicode\unicode.dll
+ install C:\Users\user\AppData\Local\Temp\bin\ServerBrowser.lib (from build\serverbrowser\ServerBrowser.lib)
+ install C:\Users\user\AppData\Local\Temp\bin\ServerBrowser.pdb (from build\serverbrowser\ServerBrowser.pdb)
+ install C:\Users\user\AppData\Local\Temp\bin\ServerBrowser.dll (from build\serverbrowser\ServerBrowser.dll)
+ install C:\Users\user\AppData\Local\Temp\bin\studiorender.lib (from build\studiorender\studiorender.lib)
+ install C:\Users\user\AppData\Local\Temp\bin\studiorender.pdb (from build\studiorender\studiorender.pdb)
+ install C:\Users\user\AppData\Local\Temp\bin\studiorender.dll (from build\studiorender\studiorender.dll)
+ install C:\Users\user\AppData\Local\Temp\bin\vgui2.lib (from build\vgui2\src\vgui2.lib)
+ install C:\Users\user\AppData\Local\Temp\bin\vgui2.pdb (from build\vgui2\src\vgui2.pdb)
+ install C:\Users\user\AppData\Local\Temp\bin\vgui2.dll (from build\vgui2\src\vgui2.dll)
+ install C:\Users\user\AppData\Local\Temp\bin\video_services.lib (from build\video\video_services.lib)
+ install C:\Users\user\AppData\Local\Temp\bin\video_services.pdb (from build\video\video_services.pdb)
+ install C:\Users\user\AppData\Local\Temp\bin\video_services.dll (from build\video\video_services.dll)
   Creando biblioteca C:\msys64\home\user\happydoge\source-engine\build\launcher_main\hl2_launcher.lib y objeto C:\msys64\home\user\happydoge\source-engine\build\launcher_main\hl2_launcher.exp

   Creando biblioteca unicode\unicode.lib y objeto unicode\unicode.exp

+ install C:\Users\user\AppData\Local\Temp\hl2_launcher.pdb (from build\launcher_main\hl2_launcher.pdb)
+ install C:\Users\user\AppData\Local\Temp\hl2_launcher.exe (from build\launcher_main\hl2_launcher.exe)
+ install C:\Users\user\AppData\Local\Temp\bin\unicode.lib (from build\unicode\unicode.lib)
+ install C:\Users\user\AppData\Local\Temp\bin\unicode.pdb (from build\unicode\unicode.pdb)
+ install C:\Users\user\AppData\Local\Temp\bin\unicode.dll (from build\unicode\unicode.dll)
   Creando biblioteca vguimatsurface\vguimatsurface.lib y objeto vguimatsurface\vguimatsurface.exp

+ install C:\Users\user\AppData\Local\Temp\bin\vguimatsurface.lib (from build\vguimatsurface\vguimatsurface.lib)
+ install C:\Users\user\AppData\Local\Temp\bin\vguimatsurface.pdb (from build\vguimatsurface\vguimatsurface.pdb)
+ install C:\Users\user\AppData\Local\Temp\bin\vguimatsurface.dll (from build\vguimatsurface\vguimatsurface.dll)
   Creando biblioteca vphysics\vphysics.lib y objeto vphysics\vphysics.exp

+ install C:\Users\user\AppData\Local\Temp\bin\vphysics.lib (from build\vphysics\vphysics.lib)
+ install C:\Users\user\AppData\Local\Temp\bin\vphysics.pdb (from build\vphysics\vphysics.pdb)
+ install C:\Users\user\AppData\Local\Temp\bin\vphysics.dll (from build\vphysics\vphysics.dll)
Waf: Leaving directory `C:\msys64\home\user\happydoge\source-engine\build'
'install' finished successfully (3m54.322s)
```
<br/><br/>
Ok, right now, making MSVC solution is a great challenge. It was told that Clang could be used and applied alternatively, if MSVC needs a ton of fixes.

**Comment by LegendaryGuard** [comment]
Before that, a documentation is required. 'Cause Python was required before building. Moreover requires MSVC, but I used Windows SDK 10.0.20348.0, looks like it's VS2022, and I built with x86. I'll try with `--64bits` parameter in waf.

**Comment by LegendaryGuard** [comment]
I just tested with `waf.bat configure -T debug --64bits`. Here the log with this execution:
```batch
C:\msys64\home\user\happydoge\source-engine> .\waf.bat configure -T debug --64bits
Página de códigos activa: 1252
Using python
Setting top to                                          : C:\msys64\home\user\happydoge\source-engine
Setting out to                                          : C:\msys64\home\user\happydoge\source-engine\build
Build type                                              : debug
LTO build                                               : no
PolyOpt build                                           : no
Checking for 'msvc' (C compiler)                        : C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64\CL.exe
Target OS                                               : win32
Target CPU                                              : amd64
Target binfmt                                           : pe
Checking for 'msvc' (C++ compiler)                      : C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64\CL.exe
Target OS                                               : win32
Target CPU                                              : amd64
Target binfmt                                           : pe
Checking for program 'git'                              : C:\Program Files\Git\cmd\git.exe
Checking git hash                                       : 062596c-dirty
Checking if 'msvc' can target 32-bit                    : no
Checking for library libz                               : yes
Checking for library SDL2                               : yes
Checking for library libjpeg                            : yes
Checking for library libpng                             : yes
Checking for library d3dx9                              : yes
Checking for library d3d9                               : yes
Checking for library dsound                             : yes
Checking for library dxguid                             : yes
--> appframework                                        : in progress
<-- appframework                                        : done
--> bitmap                                              : in progress
<-- bitmap                                              : done
--> choreoobjects                                       : in progress
<-- choreoobjects                                       : done
--> datacache                                           : in progress
<-- datacache                                           : done
--> datamodel                                           : in progress
<-- datamodel                                           : done
--> dmxloader                                           : in progress
<-- dmxloader                                           : done
--> engine                                              : in progress
<-- engine                                              : done
--> engine/voice_codecs/minimp3                         : in progress
<-- engine/voice_codecs/minimp3                         : done
--> filesystem                                          : in progress
<-- filesystem                                          : done
--> game/client                                         : in progress
<-- game/client                                         : done
--> game/server                                         : in progress
<-- game/server                                         : done
--> gameui                                              : in progress
<-- gameui                                              : done
--> inputsystem                                         : in progress
<-- inputsystem                                         : done
--> ivp/havana                                          : in progress
<-- ivp/havana                                          : done
--> ivp/havana/havok/hk_base                            : in progress
<-- ivp/havana/havok/hk_base                            : done
--> ivp/havana/havok/hk_math                            : in progress
<-- ivp/havana/havok/hk_math                            : done
--> ivp/ivp_compact_builder                             : in progress
<-- ivp/ivp_compact_builder                             : done
--> ivp/ivp_physics                                     : in progress
<-- ivp/ivp_physics                                     : done
--> launcher                                            : in progress
<-- launcher                                            : done
--> launcher_main                                       : in progress
<-- launcher_main                                       : done
--> materialsystem                                      : in progress
<-- materialsystem                                      : done
--> materialsystem/shaderapidx9                         : in progress
<-- materialsystem/shaderapidx9                         : done
--> materialsystem/shaderlib                            : in progress
<-- materialsystem/shaderlib                            : done
--> materialsystem/stdshaders                           : in progress
<-- materialsystem/stdshaders                           : done
--> mathlib                                             : in progress
<-- mathlib                                             : done
--> particles                                           : in progress
<-- particles                                           : done
--> scenefilecache                                      : in progress
<-- scenefilecache                                      : done
--> serverbrowser                                       : in progress
<-- serverbrowser                                       : done
--> soundemittersystem                                  : in progress
<-- soundemittersystem                                  : done
--> studiorender                                        : in progress
<-- studiorender                                        : done
--> thirdparty/StubSteamAPI                             : in progress
<-- thirdparty/StubSteamAPI                             : done
--> tier0                                               : in progress
<-- tier0                                               : done
--> tier1                                               : in progress
<-- tier1                                               : done
--> tier2                                               : in progress
<-- tier2                                               : done
--> tier3                                               : in progress
<-- tier3                                               : done
--> vgui2/matsys_controls                               : in progress
<-- vgui2/matsys_controls                               : done
--> vgui2/src                                           : in progress
<-- vgui2/src                                           : done
--> vgui2/vgui_controls                                 : in progress
<-- vgui2/vgui_controls                                 : done
--> vgui2/vgui_surfacelib                               : in progress
<-- vgui2/vgui_surfacelib                               : done
--> vguimatsurface                                      : in progress
<-- vguimatsurface                                      : done
--> video                                               : in progress
<-- video                                               : done
--> vphysics                                            : in progress
<-- vphysics                                            : done
--> vpklib                                              : in progress
<-- vpklib                                              : done
--> vstdlib                                             : in progress
<-- vstdlib                                             : done
--> vtf                                                 : in progress
<-- vtf                                                 : done
--> unicode                                             : in progress
<-- unicode                                             : done
--> utils/bzip2                                         : in progress
<-- utils/bzip2                                         : done
'configure' finished successfully (5.060s)
```
<br/><br/>
After that, I run `waf.bat build` and finished with errors (reached to [ 148/2214]), here the build log:
[build_win64_log.txt](https://github.com/nillerusr/source-engine/files/9212631/build_win64_log.txt)

**Comment by LegendaryGuard** [comment]
About `createallprojects.bat`, there's some file missing and still cannot generate the MSVC solution. Log:
[msvc_createallprojects_log.txt](https://github.com/nillerusr/source-engine/files/9212664/msvc_createallprojects_log.txt)

**Comment by HappyDOGE** [comment]
createallprojects is legacy vpc, if you want to create a solution use `waf msvs`

**Comment by LegendaryGuard** [comment]
I updated to the last commit right now, using `waf.bat configure -T debug --64bits` and after when building with `waf.bat build` stops at [ 160/2214]<br/>
Log:
[build_win64_log_2.txt](https://github.com/nillerusr/source-engine/files/9212741/build_win64_log.txt)

**Comment by HappyDOGE** [comment]
win64 is not supported at the moment

**Comment by LegendaryGuard** [comment]
> win64 is not supported at the moment

Ok. Even could be a priority for the nowadays and future computers.

About `waf msvs`, I generated the solution, I opened with VS2022, I built and it failed. <br/>
Log: [msvc_vs2022_build_log.txt](https://github.com/nillerusr/source-engine/files/9212789/msvc_vs2022_build_log.txt)

How the solution is:
msvc_lg_build_vs2022

**Pull request merged**
