### PR TITLE
GitHub Actions CI

### PR DESCRIPTION
**Pull request by Margen67**
currently fails: https://github.com/Margen67/source-engine/actions/runs/798632987
macOS support is impossible unless 64-bit is supported.

### CODE REVIEW

**Comment by nillerusr** [comment]
At the moment waf is only configured for build for linux and partially android.

**Comment by nillerusr** [comment]
And 64 bit is supported, but i don't test it

**Comment by Margen67** [comment]
Is Visual Studio 2017/2019 supported or only VS2013/2015?

**Comment by nillerusr** [comment]
Better to use older version

**Comment by Margen67** [comment]
> 
> 
> Do yoy want automatically building?

Yes.

**Comment by abasgames** [comment]
https://github.com/q4a/source-engine/actions/runs/869026649

**Pull request closed without merging**
